version: '3.8'

services:
  whisper-notion:
    build: .
    volumes:
      - ./input:/app/input
      - ./output:/app/output
      - ./logs:/app/logs
      - ./config.yaml:/app/config.yaml:ro
    env_file:
      - .env
    environment:
      - DEVICE=${DEVICE:-cpu}
    command: ["python", "run.py", "monitor"]
    restart: unless-stopped

  # Optional: Ollama service for local LLM
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

volumes:
  ollama_data: